### PR TITLE
Add ability to update hook handlers (aka rehook)

### PR DESCRIPTION
**Pull request by FireSiku**
This PR adds the ability to update the hook handler for any given hook, without affecting their position in the hook chain. 

Also contains some code refactoring following UnShame's advice.

### CODE REVIEW

**Comment by Dreomite** [comment]
It would be better to leave current behavior for rehooking (showing a warning and not letting to overwrite an old hook). But still, give a possibility to rehook functions when calling a hooking function with `true` after the `handler`. Is it easy to implement?

**Comment by FireSiku** [comment]
It is easy to implement, but also wrong. Using boolean arguments to dictate behavior of a function can easily lead to bad code and future on, unmaintainable code nobody understands. If we decide to have that optional feature as a boolean, we should use one to let hooks be enabled or disabled by default. Why are we not using a boolean to indicate a hook should be delayed and if false, showing an error if it cant be hooked immediately. Should we be thinking about using a boolean to add other new features?

And then before you know it, because you followed the same logic to stack on optional features as booleans, you end up with horrors like these:
```lua
mod:hook("ChatManager", "register_channel", function(self, ...)
    -- function code here
end, true nil, true, true, nil, true)
```

Oh yeah also, that's an hook_origin call. I mean, it's painfully obviously to anyone looking at this function that the 7th argument is true.

**Comment by unshame** [comment]
I think for debug params it's fine

**Comment by unshame** [comment]
The other option is to have that as a mod_data option. allow_rehooking = true/false  
Considering the usecase for this feature, I think this is better.

**Comment by FireSiku** [comment]
Storing it in mod_data sounds like a great idea to me. Leaves it to the mod author to turn on certain "debug features" of VMF.

**Comment by FireSiku** [comment]
My initial suggestion when I heard this feature was needed was to implement `mod:hook_replace`

Then I was told it was a bad idea, because it is never done except for debugging, and your debugging process involves reloading a single file which will end up calling all the `mod:hook` again and spamming errors in the console log.

It seems like adding `allow_rehooking = true` to mod_data would satisfy your needs without needing to turn all of your hooks into a jumbled mess of if-then-else blocks.

**Comment by unshame** [comment]
We can always add explicit :rehook functions if there's a need for it. Implicit rehooking is what's been requested, and since this was a feature and it didn't cause any problems, I don't see why it's bad design to readd it with a toggle.  
The reason to disable it is to prevent accidental rehooking. You only need to enable it if you do something out of the ordinary like reloading a file with dofile.

**Pull request merged**
